rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :balances

  root 'main#index'

  get '/party' => 'party#index'

  get '/join_party/:id'  => 'party#join'
  get '/leave_party/:id(/:user_id)' => 'party#leave'
  get '/create_party'    => 'party#create'
  get '/send_invite_to_party/:id'     => 'party#send_invite_to_party'
  get '/get_party_users/:id'  => 'party#get_users'

  get '/send_invite' => 'main#send_invite'
  get '/access_denied' => 'main#access_denied_for_party', as: :access_denied_for_party
  get '/access_denied_party' => 'main#access_denied_for_party_exists', as: :access_denied_for_party_exists
  get '/invite_sent' => 'main#invite_sent', as: :invite_sent_page

  get '/out' => 'session#out'

  post '/auth/:provider/callback', to: 'session#create'

  resources :users

end

rails_app/app/models/balance.rb
class Balance < ActiveRecord::Base
end

rails_app/app/controllers/balances_controller.rb
#coding utf-8
class BalancesController < ApplicationController
  before_action :set_balance, only: [:show, :edit, :update, :destroy]

  # GET /balances
  # GET /balances.json
  def index
    @balances = Balance.all
  end

  # GET /balances/1
  # GET /balances/1.json
  def show
  end

  # GET /balances/new
  def new
    @balance = Balance.new
  end

  # GET /balances/1/edit
  def edit
  end

  # POST /balances
  # POST /balances.json
  def create
    @balance = Balance.new(balance_params)

    respond_to do |format|
      if @balance.save
        format.html { redirect_to @balance, notice: 'Balance was successfully created.' }
        format.json { render :show, status: :created, location: @balance }
      else
        format.html { render :new }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balances/1
  # PATCH/PUT /balances/1.json
  def update
    respond_to do |format|
      if @balance.update(balance_params)
        format.html { redirect_to @balance, notice: 'Balance was successfully updated.' }
        format.json { render :show, status: :ok, location: @balance }
      else
        format.html { render :edit }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balances/1
  # DELETE /balances/1.json
  def destroy
    @balance.destroy
    respond_to do |format|
      format.html { redirect_to balances_url, notice: 'Balance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balance
      @balance = Balance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def balance_params
      params.require(:balance).permit(:port, :login, :password)
    end
end

rails_app/app/helpers/balances_helper.rb
#coding utf-8
module BalancesHelper
	def get_status(port)
		begin
	        RestClient.get("http://localhost:#{port}")
	        true
	    rescue Exception => msg
	        false
	    end
	end
end

rails_app/app/views/balances/_form.html.erb
<%= form_for(@balance) do |f| %>
  <% if @balance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@balance.errors.count, "error") %> prohibited this balance from being saved:</h2>

      <ul>
      <% @balance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :port %><br>
    <%= f.number_field :port %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/balances/edit.html.erb
<h1>Editing balance</h1>

<%= render 'form' %>

<%= link_to 'Show', @balance %> |
<%= link_to 'Back', balances_path %>

rails_app/app/views/balances/index.html.erb
<h1>Listing balances</h1>

<table>
  <thead>
    <tr>
      <th>Port</th>
      <!--th>Login</th>
      <th>Password</th-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @balances.each_with_index do |balance, index| %>
      <tr>
        <td><%= balance.port %></td>
        <!--td><%= balance.login %></td>
        <td><%= balance.password %></td-->
        <td><%= (get_status(balance.port)) ? "Доступен" : "Не доступен" %></td>
        <td><%= link_to 'Show', balance %></td>
        <td><%= link_to 'Edit', edit_balance_path(balance) %></td>
        <td><%= link_to 'Destroy', balance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Balance', new_balance_path %>

rails_app/app/views/balances/new.html.erb
<h1>New balance</h1>

<%= render 'form' %>

<%= link_to 'Back', balances_path %>

rails_app/app/views/balances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Port:</strong>
  <%= @balance.port %>
</p>

<p>
  <strong>Login:</strong>
  <%= @balance.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @balance.password %>
</p>

<%= link_to 'Edit', edit_balance_path(@balance) %> |
<%= link_to 'Back', balances_path %>